In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [2]:
data_path = os.path.join('Resources', 'canada_population.csv')
ontario = pd.read_csv(data_path)
ontario = ontario[["When", "Ontario"]]
ontario["REF_DATE"] = ontario["When"].str[-4:]
ontario = ontario[["Ontario", "REF_DATE"]]
ontario["REF_DATE"] = ontario["REF_DATE"].astype(int)
ontario = ontario.drop_duplicates(subset=["REF_DATE"], keep='last')
ontario = ontario.loc[(ontario["REF_DATE"] >= 1998)&
                     (ontario["REF_DATE"] <= 2013), :]
ontario

        Ontario  REF_DATE
211  11408804.0      1998
215  11559464.0      1999
219  11748348.0      2000
223  11962187.0      2001
227  12145310.0      2002
231  12290132.0      2003
235  12436416.0      2004
239  12578124.0      2005
243  12700318.0      2006
247  12806584.0      2007
251  12926563.0      2008
255  13046751.0      2009
259  13188726.0      2010
263  13316463.0      2011
267  13456709.0      2012
271  13603904.0      2013

In [4]:
data_path = os.path.join('Resources', 'ontario_impaired_driving.csv')
data = pd.read_csv(data_path)
data_clean1 = data.loc[(data["Violations"]=="Total impaired driving [910]") &
                       (data["UOM"] == "Rate") &
                       (data["Statistics"]=="Rate per 100,000 population"),:]
impaired_driving_on = data_clean1[["REF_DATE", "GEO", "Violations", "SCALAR_FACTOR", "VALUE"]]
impaired_driving_on = impaired_driving_on.loc[impaired_driving_on["REF_DATE"] <= 2018, :]
impaired_driving_on
merged_driving = pd.merge(impaired_driving_on, ontario, on="REF_DATE")
merged_driving["Impaired Driving per 100,000"] = (merged_driving["VALUE"]/merged_driving["Ontario"]) * 100000
merged_driving

,REF_DATE,GEO,Violations,SCALAR_FACTOR,VALUE,Ontario,"Impaired Driving per 100,000"
0,1998,Ontario [35],Total impaired driving [910],units,190.21,11408804.0,1.667221
1,1999,Ontario [35],Total impaired driving [910],units,194.56,11559464.0,1.683123
2,2000,Ontario [35],Total impaired driving [910],units,195.48,11748348.0,1.663894
3,2001,Ontario [35],Total impaired driving [910],units,180.55,11962187.0,1.509339
4,2002,Ontario [35],Total impaired driving [910],units,170.51,12145310.0,1.403916
5,2003,Ontario [35],Total impaired driving [910],units,155.00,12290132.0,1.261174
6,2004,Ontario [35],Total impaired driving [910],units,147.28,12436416.0,1.184264
7,2005,Ontario [35],Total impaired driving [910],units,142.86,12578124.0,1.135781
8,2006,Ontario [35],Total impaired driving [910],units,140.09,12700318.0,1.103043
9,2007,Ontario [35],Total impaired driving [910],units,140.25,12806584.0,1.095140
10,2008,Ontario [35],Total impaired driving [910],units,145.56,12926563.0,1.126053
11,2009,Ontario [35],Total impaired driving [910],units,140.08,13046751.0,1.073677
12,2010,Ontario [35],Total impaired driving [910],units,131.47,13188726.0,0.996836
13,2011,Ontario [35],Total impaired driving [910],units,129.93,13316463.0,0.975710
14,2012,Ontario [35],Total impaired driving [910],units,128.41,13456709.0,0.954245
15,2013,Ontario [35],Total impaired driving [910],units,117.09,13603904.0,0.860709

In [25]:
data_path = os.path.join('Resources', 'cannabis_usage_1961_2018.csv')
data = pd.read_csv(data_path)
data_clean1 = data.loc[(data["Frequency of use"]=="Total, all frequencies") &
                       (data["UOM"] == "Persons"),:]
data_clean = data_clean1.groupby("REF_DATE").sum()
data_clean = data_clean[["VALUE"]]
data_clean.reset_index()
merged_cannabis = pd.merge(data_clean, ontario, on="REF_DATE")
merged_cannabis["Impaired Driving per 100,000"] = (merged_cannabis["VALUE"]/merged_cannabis["Ontario"]) * 100000
merged_cannabis

    REF_DATE      VALUE     Ontario  Impaired Driving per 100,000
0       1998  5435089.0  11408804.0                  47639.428287
1       1999  5691608.0  11559464.0                  49237.646313
2       2000  5934113.0  11748348.0                  50510.190880
3       2001  6150678.0  11962187.0                  51417.671367
4       2002  6334251.0  12145310.0                  52153.884915
5       2003  6486339.0  12290132.0                  52776.805001
6       2004  6614687.0  12436416.0                  53188.048711
7       2005  6729831.0  12578124.0                  53504.250713
8       2006  6842080.0  12700318.0                  53873.296716
9       2007  6963874.0  12806584.0                  54377.295304
10      2008  7107408.0  12926563.0                  54982.968017
11      2009  7283378.0  13046751.0                  55825.224226
12      2010  7498390.0  13188726.0                  56854.543797
13      2011  7756525.0  13316463.0                  58247.636779
14      2012  8054186.0  13456709.0                  59852.568708
15      2013  8382022.0  13603904.0                  61614.827626